CTQM_MEC/Controllers/GiaoDichesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CTQM_Car.Data;
using CTQM_MEC.Data;
using CTQM_MEC.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Twilio.TwiML.Voice;

namespace CTQM_MEC.Controllers
{
    public class GiaoDichesController : Controller
    {
        private readonly CTQMDbContext _context;

        public GiaoDichesController(CTQMDbContext context)
        {
            _context = context;
        }

        [Authorize]
        public async Task<IActionResult> Shopping(int? id)
        {
            CartModelView cmv = new CartModelView();
            if (id != null)
            {
                cmv.MaKhachHang = id;
                double tong = 0;
				var GH = from x in _context.Giaodichs
                         where x.MaKhachHang == id
						  select x;
				List<GiaoDich> GHList = GH.ToList();
                List<Xe> XeList = new List<Xe>();
                for (int i = 0; i < GHList.Count; i++)
                {
					var Car = await _context.Xe.FindAsync(GHList[i].MaXe);
                    tong += Car.GiaThanh;
					XeList.Add(Car);
                }
                cmv.ListXe = XeList;
                cmv.TongTien = tong;
                return View("Cart", cmv);
            }
            return RedirectToAction("Index", "Home");
        }

        // Thêm vào giỏ hàng, nếu đã thêm rồi thì chỉ cập nhật lại số lượng
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddToCart(ShopModelView smv)
        {
            if (smv != null)
            {
                var GDC = from x in _context.Giaodichs
                          select x;
                GDC = GDC.Where(s => s.MaXe == smv.MaXe);
                GDC = GDC.Where(s => s.MaKhachHang == smv.MaKhachHang);
                List<GiaoDich> GDlist = GDC.ToList();
                if (GDlist.Count == 0)
                {
                    GiaoDich gd = new GiaoDich();
                    gd.MaKhachHang = (int)smv.MaKhachHang;
                    gd.MaXe = (int)smv.MaXe;
                    gd.SoLuongMua = 1;
                    gd.TongTien = (double)(smv.GiaThanh * 1);

                    _context.Add(gd);
                    await _context.SaveChangesAsync();
                    ViewData["ResultGoodMessage"] = "Add to your pocket";
                    return RedirectToAction("Shopping", new { id = (int)smv.MaKhachHang});
                }
            }
            ViewData["ResultBadMessage"] = "We out of stock";
            return RedirectToAction("Shopping", "Xes", new { id = (int)smv.MaXe });
        }

        // GET: GiaoDiches
        public async Task<IActionResult> Index()
        {
            var cTQMDbContext = _context.Giaodichs.Include(g => g.KhachHang).Include(g => g.Xe);
            return View(await cTQMDbContext.ToListAsync());
        }

        // GET: GiaoDiches/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Giaodichs == null)
            {
                return NotFound();
            }

            var giaoDich = await _context.Giaodichs
                .Include(g => g.KhachHang)
                .Include(g => g.Xe)
                .FirstOrDefaultAsync(m => m.MaGiaoDich == id);
            if (giaoDich == null)
            {
                return NotFound();
            }

            return View(giaoDich);
        }

        // GET: GiaoDiches/Create
        public IActionResult Create()
        {
            ViewData["MaKhachHang"] = new SelectList(_context.KhachHangs, "MaKhachHang", "GiayPhepLaiXe");
            ViewData["MaXe"] = new SelectList(_context.Xe, "MaXe", "HangXe");
            return View();
        }

        // POST: GiaoDiches/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaGiaoDich,MaKhachHang,MaXe,SoLuongMua,TongTien")] GiaoDich giaoDich)
        {
            if (ModelState.IsValid)
            {
                _context.Add(giaoDich);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaKhachHang"] = new SelectList(_context.KhachHangs, "MaKhachHang", "GiayPhepLaiXe", giaoDich.MaKhachHang);
            ViewData["MaXe"] = new SelectList(_context.Xe, "MaXe", "HangXe", giaoDich.MaXe);
            return View(giaoDich);
        }

        // GET: GiaoDiches/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Giaodichs == null)
            {
                return NotFound();
            }

            var giaoDich = await _context.Giaodichs.FindAsync(id);
            if (giaoDich == null)
            {
                return NotFound();
            }
            ViewData["MaKhachHang"] = new SelectList(_context.KhachHangs, "MaKhachHang", "GiayPhepLaiXe", giaoDich.MaKhachHang);
            ViewData["MaXe"] = new SelectList(_context.Xe, "MaXe", "HangXe", giaoDich.MaXe);
            return View(giaoDich);
        }

        // POST: GiaoDiches/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaGiaoDich,MaKhachHang,MaXe,SoLuongMua,TongTien")] GiaoDich giaoDich)
        {
            if (id != giaoDich.MaGiaoDich)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(giaoDich);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GiaoDichExists(giaoDich.MaGiaoDich))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaKhachHang"] = new SelectList(_context.KhachHangs, "MaKhachHang", "GiayPhepLaiXe", giaoDich.MaKhachHang);
            ViewData["MaXe"] = new SelectList(_context.Xe, "MaXe", "HangXe", giaoDich.MaXe);
            return View(giaoDich);
        }

        // GET: GiaoDiches/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Giaodichs == null)
            {
                return NotFound();
            }

            var giaoDich = await _context.Giaodichs
                .Include(g => g.KhachHang)
                .Include(g => g.Xe)
                .FirstOrDefaultAsync(m => m.MaGiaoDich == id);
            if (giaoDich == null)
            {
                return NotFound();
            }

            return View(giaoDich);
        }

        // POST: GiaoDiches/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, CartModelView cmv)
        {
            if (_context.Giaodichs == null)
            {
                return Problem("Entity set 'CTQMDbContext.Giaodichs'  is null.");
            }
            var giaoDich = await _context.Giaodichs
               .FirstOrDefaultAsync(m => m.MaXe == id && m.MaKhachHang == cmv.MaKhachHang);
            if (giaoDich != null)
            {
                _context.Giaodichs.Remove((GiaoDich)giaoDich);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction("Shopping", new { id = (int)cmv.MaKhachHang });
        }

        private bool GiaoDichExists(int id)
        {
          return _context.Giaodichs.Any(e => e.MaGiaoDich == id);
        }
    }
}

CTQM_MEC/Controllers/HoaDonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CTQM_Car.Data;
using CTQM_MEC.Data;
using System.Security.Cryptography.X509Certificates;
using PayPal.Core;
using PayPal.v1.Payments;
using BraintreeHttp;
using Microsoft.AspNetCore.Authorization;
using CTQM_MEC.Models;
using System.ComponentModel.DataAnnotations;
using Twilio.TwiML.Voice;

namespace CTQM_MEC.Controllers
{
    public class HoaDonsController : Controller
    {
        private readonly CTQMDbContext _context;
        private readonly string _clientId;
        private readonly string _secretKey;


        public double TyGia = 23300;
        public HoaDonsController(CTQMDbContext context, IConfiguration config)
        {
            _context = context;
            _clientId = config["PaypalSettings:ClientId"];
            _secretKey = config["PaypalSettings:SecretKey"];
        }

        public async Task<IActionResult> PaypalCheckout(int? id)
        {
            var environment = new SandboxEnvironment(_clientId, _secretKey);
            var client = new PayPalHttpClient(environment);

            #region Create Paypal Order
            var itemList = new ItemList()
            {
                Items = new List<Item>()
            };
            double tong = 0;
            var GH = from x in _context.Giaodichs
                     where x.MaKhachHang == id
                     select x;
            List<GiaoDich> GHList = GH.ToList();
            for(int i = 0; i < GHList.Count; i++)
            {
		        var Car = await _context.Xe.FindAsync(GHList[i].MaXe);
                tong += Car.GiaThanh;
                itemList.Items.Add(new Item()
                {
                    Name = Car.TenXe,
                    Currency = "USD",
                    Price = Math.Round(Car.GiaThanh / TyGia, 2).ToString(),
                    Quantity = "1",
                    Sku = "sku",
                    Tax = "0"
                });
            }
            var total = Math.Round(tong/ TyGia, 2).ToString();
            #endregion
            var paypalOrderId = DateTime.Now.Ticks;
            var hostName = $"{HttpContext.Request.Scheme}://{HttpContext.Request.Host}";
            var payment = new Payment()
            {
                Intent = "sale",
                Transactions = new List<Transaction>()
                {
                    new Transaction()
                    {
                        Amount = new Amount()
                        {
                            Total = total.ToString(),
                            Currency = "USD",
                            Details = new AmountDetails
                            {
                                Tax = "0",
                                Shipping = "0",
                                Subtotal = total.ToString()
                            }
                        },
                        ItemList = itemList,
                        Description = $"Invoice #{paypalOrderId}",
                        InvoiceNumber = paypalOrderId.ToString()
                    }
                },
                RedirectUrls = new RedirectUrls()
                {
                    CancelUrl = $"{hostName}/hoadons/CheckoutFail",
                    ReturnUrl = $"{hostName}/hoadons/InHoaDon/{id}"
                },
                Payer = new Payer()
                {
                    PaymentMethod = "paypal"
                }
            };

            var request = new PaymentCreateRequest();
            request.RequestBody(payment);

            try
            {
                var response = await client.Execute(request);
                var statusCode = response.StatusCode;
                Payment result = response.Result<Payment>();

                var links = result.Links.GetEnumerator();
                string paypalRedirectUrl = null;
                while (links.MoveNext())
                {
                    LinkDescriptionObject lnk = links.Current;
                    if (lnk.Rel.ToLower().Trim().Equals("approval_url"))
                    {
                        //saving the payapalredirect URL to which user will be redirected for payment  
                        paypalRedirectUrl = lnk.Href;
                    }
                }
                return Redirect(paypalRedirectUrl);
            }
            catch (HttpException httpException)
            {
                var statusCode = httpException.StatusCode;
                var debugId = httpException.Headers.GetValues("PayPal-Debug-Id").FirstOrDefault();

                //Process when Checkout with Paypal fails
                return Redirect("/hoadons/CheckoutFail");
            }

        }

        public IActionResult CheckoutFail()
        {
            return View();
        }
        public IActionResult CheckoutSuccess()
        {
            return View();
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        public async Task<IActionResult> ThanhToan(int? id)
        {
            CartModelView cmv = new CartModelView();
            if (id != null)
            {
                cmv.MaKhachHang = id;
                double tong = 0;
                var GH = from x in _context.Giaodichs
                         where x.MaKhachHang == id
                         select x;
                List<GiaoDich> GHList = GH.ToList();
                if (GHList.Count > 0)
                {
                    List<Xe> XeList = new List<Xe>();
                    for (int i = 0; i < GHList.Count; i++)
                    {
                        var Car = await _context.Xe.FindAsync(GHList[i].MaXe);
                        tong += Car.GiaThanh;
                        XeList.Add(Car);
                    }
                    cmv.ListXe = XeList;
                    // + 30tr tiền thuế :)
                    cmv.TongTien = tong + (10000000 * GHList.Count);
                    return View("ThanhToan", cmv);
                }
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        public async Task<IActionResult> InHoaDon(int? id)
        {
            if (id != null)
            {
                var GH = from x in _context.Giaodichs
                         where x.MaKhachHang == id
                         select x;
                List<GiaoDich> GHList = GH.ToList();
                for (int i = 0; i < GHList.Count;i++)
                {
                    HoaDon hd = new HoaDon();
                    hd.MaKhachHang = GHList[i].MaKhachHang;
                    hd.MaXe = GHList[i].MaXe;
                    hd.TongSoLuong = GHList[i].SoLuongMua;
                    hd.ThanhTien = GHList[i].TongTien + 10000000;
                    hd.NgayThanhToan = DateTime.Today;
                    hd.PhuongThucThanhToan = "PayPal";
                    _context.Add(hd);
                    var giaoDich = await _context.Giaodichs
                    .FirstOrDefaultAsync(m => m.MaGiaoDich == GHList[i].MaGiaoDich);
                    if (giaoDich != null)
                    {
                        _context.Giaodichs.Remove((GiaoDich)giaoDich);
                    }
                    await _context.SaveChangesAsync();
                    //Paypal
                    // Hoá đơn dựa vào mã khách hàng khớp vd 1 
                    // 2 xe A B
                    // 1 A B
                    // A 1
                    // B 1
                }
                return View("CheckoutSuccess");
            }
            return RedirectToAction("Index", "Home");
        }

        // POST: HoaDons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.HoaDons == null)
            {
                return Problem("Entity set 'CTQMDbContext.HoaDons'  is null.");
            }
            var hoaDon = await _context.HoaDons.FindAsync(id);
            if (hoaDon != null)
            {
                _context.HoaDons.Remove(hoaDon);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HoaDonExists(int id)
        {
          return _context.HoaDons.Any(e => e.MaHoaDon == id);
        }
    }
}

CTQM_MEC/Views/GiaoDiches/Cart.cshtml
@using System.Security.Claims
@model CTQM_MEC.Models.CartModelView

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Carrt</title>
    <link rel="stylesheet" type="text/css" href="cart.css">
    <link href="~/css/giohang.css" rel="stylesheet" />
</head>
<body>
    <div class="page">
        <div id="cart" class="cart-page commerce-apple-pay-data" data-environment="prod" data-enable-edit-size-in-cart="false">
            <div class="cart__container tds-content_container" style="margin-top:50px; height:500px;">
                <div class="cart__header ">
                    <h1>Cart</h1>
                </div>
                <div class="tds-flex tds-flex-gutters line-item-and-order">
                    <div class="tds-flex-item">
                        <div class="lineitems__container">
                            @foreach (var item in Model.ListXe)
                            {
                            <div class="lineitem__container tds-flex tds-flex-gutters">
                                <div class="lineitem__main-info">
                                    <div class="lineitem__image tds-flex-item">
                                        <img src="~/images/Car/@item.TenXe/2.png" alt="Model S All-Weather Interior Liners">
                                    </div>
                                    @if (ViewData["ResultBadMessage"] != null)
                                        {
                                            <br />
                                            <label style="color: red;">@ViewData["ResultBadMessage"]</label>
                                            <br />
                                        }
                                        @if (ViewData["ResultGoodMessage"] != null)
                                        {
                                            <br />
                                            <label style="color: green;">@ViewData["ResultGoodMessage"]</label>
                                            <br />
                                        }
                                    <div class="lineitem__data tds-flex-item">
                                            <p class="lineitem__name tds-text--500" id="0-1669541-00-A">@item.TenXe</p>
                                            <p class="lineitem__option-display-name">@item.HangXe</p>
                                            <div class="lineitem__qty">
                                                <div class="lineitem__editable-item">
                                                    <span>Quantity: </span>
                                                    <div class="lineitem__dropdown">
                                                        <div class="tds-tooltip-wrapper tds-tooltip-wrapper--inline" aria-label="Quantity: " aria-describedby="0-1669541-00-A">
                                                            <button style="border: none;" aria-haspopup="listbox" class="tds-dropdown-trigger" type="button">
                                                                <div class="custom-select" style="width:50px;">
                                                                    <select>
                                                                    <option value="1">1</option>
                                                                    </select>
                                                                </div>
                                                            </button>
                                                        </div>
                                                    </div>
                                                </div>
                                                <button style="border: none; border-bottom: 1px solid" class="w3-button w3-black w3-margin-bottom" onclick="document.getElementById('RemoveModal').style.display='block'">Remove</button>
                                        <!-- phan trong remove -->
                                        <div id="RemoveModal" class="modal js-modal" style="display: none;">
                                            <div class="modal-container js-modal-container">
                                                <header class="modal-header">
                                                    <span onclick="document.getElementById('RemoveModal').style.display='none'" class="button-close">×</span>
                                                </header>
                                                <form asp-action="Delete" asp-route-id=@item.MaXe class="modal-body">
                                                <input type="number" asp-for="MaKhachHang" value=@Model.MaKhachHang style="display: none">
                                                    <div class="tds-modal-header">
                                                        <h2 style="margin: 0;">Remove Item</h2>
                                                    </div>
                                                    <section class="modal-label">
                                                        <div>
                                                            <p>Are you sure you want to remove this item from your cart?</p>
                                                        </div>
                                                    </section>
                                                    <footer class="tds-modal-footer">
                                                        <button id="Remove" aria-describedby="0-1669541-00-A">Yes, Remove</button>
                                                    </footer>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                        <div class="tds-modal-backdrop"></div>
                                    </div>
                                    <div class="lineitem__price tds-flex-item tds-flex--col_1of4">
                                        <p class="tds-text--500" translate="no">@item.GiaThanh VNĐ</p>
                                    </div>
                                </div>
                            </div>
                            }
                        </div>
                    </div>

                    <div class="tds-flex-item">
                        <div class="order-summary__container">
                            <div class="order-summary__title">
                                <h2 class="tds-text--h4">Order Summary</h2>
                            </div>
                            <div class="order-summary__info info">
                                <div class="tds-tooltip-wrapper tds-tooltip-wrapper--inline">
                                    <div>
                                        <span>Shipping</span>
                                    </div>
                                    <div class="tds-tooltip tds-tooltip--closed" role="tooltip">
                                        <p>FedEx Economy</p>
                                    </div>
                                </div>
                                <span>Free</span>
                            </div>
                            <div class="order-summary__info info">
                                <div class="tds-tooltip-wrapper tds-tooltip-wrapper--inline">
                                    <div>
                                        <span>Sales Tax</span>

                                    </div>
                                    <div class="tds-tooltip tds-tooltip--closed" role="tooltip">
                                        <p>Sale tax is calculated with shipping address in checkout</p>
                                    </div>
                                </div>
                                <span>Calculated at checkout</span>
                            </div>
                            <div class="price-summary-container">
                                <div class="order-summary__info total">
                                    <h2 class="tds-text--h4">Subtotal</h2>
                                    <h2 class="tds-text--h4" translate="no">@Model.TongTien VNĐ</h2>
                                </div>
                            </div>
                            <div class="order-summary__info checkout-button">
                                <div class="tds-btn_group tds-btn_group--vertical order-summary__info checkout">
                                    <button class="tds-btn tds-btn--primary" onclick="location.href='@Url.Action("ThanhToan", "HoaDons", new {id = @Context.User.FindFirst(ClaimTypes.SerialNumber).Value})'">Checkout</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script>


            // When the user clicks anywhere outside of the modal, close it
            var modal = document.getElementById('RemoveModal');
            window.onclick = function (event) {
                if (event.target == modal) {
                    modal.style.display = "block";
                }
            }

        </script>

</body>
</html>

CTQM_MEC/Views/GiaoDiches/Create.cshtml
@model CTQM_Car.Data.GiaoDich

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>GiaoDich</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MaKhachHang" class="control-label"></label>
                <select asp-for="MaKhachHang" class ="form-control" asp-items="ViewBag.MaKhachHang"></select>
            </div>
            <div class="form-group">
                <label asp-for="MaXe" class="control-label"></label>
                <select asp-for="MaXe" class ="form-control" asp-items="ViewBag.MaXe"></select>
            </div>
            <div class="form-group">
                <label asp-for="SoLuongMua" class="control-label"></label>
                <input asp-for="SoLuongMua" class="form-control" />
                <span asp-validation-for="SoLuongMua" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TongTien" class="control-label"></label>
                <input asp-for="TongTien" class="form-control" />
                <span asp-validation-for="TongTien" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CTQM_MEC/Views/GiaoDiches/Delete.cshtml
@model CTQM_Car.Data.GiaoDich

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GiaoDich</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KhachHang)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KhachHang.GiayPhepLaiXe)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Xe)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Xe.HangXe)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SoLuongMua)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoLuongMua)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TongTien)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TongTien)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MaGiaoDich" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CTQM_MEC/Views/GiaoDiches/Details.cshtml
@model CTQM_Car.Data.GiaoDich

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>GiaoDich</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KhachHang)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KhachHang.GiayPhepLaiXe)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Xe)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Xe.HangXe)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SoLuongMua)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoLuongMua)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TongTien)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TongTien)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.MaGiaoDich">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>