CTQM_MEC/Controllers/HomeController.cs
using CTQM_MEC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;

namespace CTQM_MEC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Login", "Access");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CTQM_MEC/Controllers/XesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CTQM_Car.Data;
using CTQM_MEC.Data;
using CTQM_MEC.Models;

namespace CTQM_MEC.Controllers
{
    public class XesController : Controller
    {
        private readonly CTQMDbContext _context;

        public XesController(CTQMDbContext context)
        {
            _context = context;
        }

        // GET: Xes
        public async Task<IActionResult> Index()
        {
              return View(await _context.Xe.ToListAsync());
        }

        // GET: XeList
        public async Task<IActionResult> Product(string? type)
        {
            XeModelView ProductXe = new XeModelView();
            var Sxe = from x in _context.Xe
                      select x;
            if (type != null)
            {
                Sxe = Sxe.Where(s => s.HangXe.Contains(type));
                ProductXe.DanhSachXe = await Sxe.ToListAsync();
                ProductXe.type = type;
                return View(ProductXe);
            }
            ProductXe.DanhSachXe = await Sxe.ToListAsync();
            ProductXe.type = "New Arrival";
            return View(ProductXe);
        }

		// GET: Xes/Details/5
		public async Task<IActionResult> Shopping(int? id)
        {
            if (id == null || _context.Xe == null)
            {
                return NotFound();
            }

            var xe = await _context.Xe.FindAsync(id);
            if (xe == null)
            {
                return NotFound();
            }
            ShopModelView ShopView = new ShopModelView();
            ShopView.ListXe = await _context.Xe.ToListAsync();
            ShopView.XeDetails = xe;
            ShopView.MoreInfo = await _context.ThongTinChiTietXes.FindAsync(id);
            ShopView.SoLuongTT = xe.SoLuong;
            return View(ShopView);
        }

        public async Task<IActionResult> Search(string? searching)
        {
            if (searching == null) return NotFound();
            var Sxe = from x in _context.Xe
                      select x;
            if (!String.IsNullOrEmpty(searching))
            {
                Sxe = Sxe.Where(s => s.TenXe.Contains(searching));
                return RedirectToAction("Product", await Sxe.ToListAsync());
            }
            return NotFound();
        }

        // GET: Xes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Xe == null)
            {
                return NotFound();
            }

            var xe = await _context.Xe
                .FirstOrDefaultAsync(m => m.MaXe == id);
            if (xe == null)
            {
                return NotFound();
            }

            return View(xe);
        }

        // GET: Xes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Xes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaXe,TenXe,HangXe,PhanKhuc,LoaiDongCo,SoLuong,GiaThanh,MoTa")] Xe xe)
        {
            if (ModelState.IsValid)
            {
                _context.Add(xe);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(xe);
        }

        // GET: Xes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Xe == null)
            {
                return NotFound();
            }

            var xe = await _context.Xe.FindAsync(id);
            if (xe == null)
            {
                return NotFound();
            }
            return View(xe);
        }

        // POST: Xes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaXe,TenXe,HangXe,PhanKhuc,LoaiDongCo,SoLuong,GiaThanh,MoTa")] Xe xe)
        {
            if (id != xe.MaXe)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(xe);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!XeExists(xe.MaXe))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(xe);
        }

        // GET: Xes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Xe == null)
            {
                return NotFound();
            }

            var xe = await _context.Xe
                .FirstOrDefaultAsync(m => m.MaXe == id);
            if (xe == null)
            {
                return NotFound();
            }

            return View(xe);
        }

        // POST: Xes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Xe == null)
            {
                return Problem("Entity set 'CTQMDbContext.Xe'  is null.");
            }
            var xe = await _context.Xe.FindAsync(id);
            if (xe != null)
            {
                _context.Xe.Remove(xe);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool XeExists(int id)
        {
          return _context.Xe.Any(e => e.MaXe == id);
        }
    }
}

CTQM_MEC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "CTQM";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Home</title>
    <link href="~/css/Home.css" rel="stylesheet" />
</head>
<body>
<div class="container">
    <div class="container_slide" >
        <video autoplay Muted  loop >
            <source src="~/videos/mec4.mp4">
        </video>
        <button class="btn" onclick="location.href='@Url.Action("Product", "Xes")'">Discover Now</button> 
    </div>  
    <div class="HOME">
        <div class="Home_Pic_Text_LEFT">
            <div class="Img">   
                <div class="Pictures_Left">
                    <img src="~/images/Home/mec1.jpg" alt="" >
                </div> 
            </div>
            <div class="Title">
                <div class="text_Left" >
                    <h1>Ngoại hình siêu xe Mercedes AMG mới nhất</h1>
                    <p >Siêu xe Mercedes AMG mới nhất có ngoại hình hầm hố và cơ bắp. Vì vậy, bên cạnh vẻ đẹp sang trọng và quyến rũ truyền thống của những chiếc xe mang thương hiệu Mercedes thì AMG còn cho vẻ đẹp khỏe khoắn. </p>
                    <div class="bttn"><a href="#"><button class="btn" onclick="location.href='@Url.Action("Product", "Xes")'">Discover Now</button></a></div>
                </div>
            </div> 
        </div>
        <div class="Home_Pic_Text_RIGHT">
            <div class="Title">
                <div class="text_right">
                    <h1>Nội thất siêu xe Mercedes AMG mới nhất</h1>
                    <p >Không gian nội thất xe Mercedes AMG mới nhất được làm từ vật liệu da cao cấp kết hợp cùng chất liệu gỗ sang trọng. Ghế ngồi hạng thương gia có đầy đủ các tiện ích cần thiết, hệ thống âm thanh và đèn chiếu sáng hiện đại,… </p>
                    <div class="bttn"><a href="#"><button class="btn" onclick="location.href='@Url.Action("Product", "Xes")'">Discover Now</button></a></div>
                </div>
            </div>
            <div class="Img">
                <div class="Pictures_Right">
                    <img src="~/images/Home/mec2.webp" alt=" "  >
                </div>
            </div>  
        </div>
    </div>
    <!-- INTRODUCE CARS -->
    <br />
    <br />
        <h1>COMING SOON!</h1>
    <div class="introduce_cars">
        <div class="intro">
            <div class ="right">
                <div class="history" >
                    <div class="history_ShopImageBox">
                        <img class="history_ShopImage" src="https://media.zigcdn.com/media/content/2021/May/eqaawdtritle.jpg" alt="CTQM">
                    </div>
                    <div class="history_ShopTextWithButton history_TextWithButton">
                        <div class="history_ShopText">
                            <p class="tds-text--500">Mercedes-Benz EQA</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="intro">
            <div class ="right">
                <div class="history" >
                    <div class="history_ShopImageBox">
                        <img class="history_ShopImage" src="https://media.zigcdn.com/media/content/2022/Dec/cover_639c64b981967.jpg" alt="CTQM">
                    </div>
                    <div class="history_ShopTextWithButton history_TextWithButton">
                        <div class="history_ShopText">
                            <p class="tds-text--500">Mercedes-Benz AMG E 53 Cabriolet</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container_footer">
        <video autoplay Muted  loop >
            <source src="~/videos/Mercedes AMG GT’s - 4K Cinematic.mp4.mp4">
        </video>
        <div class="text-block">
            <h4>You have to a file a flight plan before leaving the driveway</h4>
            <p>Slide into the cockpit of the all-new Mercedes-Benz SLS AMG and the G-Force is guaranteed to keep you there. The first vehicle engineered completely in-house at AMG, its passinate design is destined to become a future classic. Its 563 hp engine accelerates from 0 to 100 km/h in just 3.8 seconds. Faster than a supersonic jet. No really, it is. And its lightweight aluminium frame, long sleek hood, and unmistakable gullwing doors turn heads just as fast.   </p>
        </div>
    </div>
</div>
</body>
</html>