CTQM_MEC/Controllers/GiaoDichesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CTQM_Car.Data;
using CTQM_MEC.Data;
using CTQM_MEC.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Twilio.TwiML.Voice;

namespace CTQM_MEC.Controllers
{
    public class GiaoDichesController : Controller
    {
        private readonly CTQMDbContext _context;

        public GiaoDichesController(CTQMDbContext context)
        {
            _context = context;
        }

        [Authorize]
        public async Task<IActionResult> Shopping(int? id)
        {
            CartModelView cmv = new CartModelView();
            if (id != null)
            {
                cmv.MaKhachHang = id;
                double tong = 0;
				var GH = from x in _context.Giaodichs
                         where x.MaKhachHang == id
						  select x;
				List<GiaoDich> GHList = GH.ToList();
                List<Xe> XeList = new List<Xe>();
                for (int i = 0; i < GHList.Count; i++)
                {
					var Car = await _context.Xe.FindAsync(GHList[i].MaXe);
                    tong += Car.GiaThanh;
					XeList.Add(Car);
                }
                cmv.ListXe = XeList;
                cmv.TongTien = tong;
                return View("Cart", cmv);
            }
            return RedirectToAction("Index", "Home");
        }

        // Thêm vào giỏ hàng, nếu đã thêm rồi thì chỉ cập nhật lại số lượng
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddToCart(ShopModelView smv)
        {
            if (smv != null)
            {
                var GDC = from x in _context.Giaodichs
                          select x;
                GDC = GDC.Where(s => s.MaXe == smv.MaXe);
                GDC = GDC.Where(s => s.MaKhachHang == smv.MaKhachHang);
                List<GiaoDich> GDlist = GDC.ToList();
                if (GDlist.Count == 0)
                {
                    GiaoDich gd = new GiaoDich();
                    gd.MaKhachHang = (int)smv.MaKhachHang;
                    gd.MaXe = (int)smv.MaXe;
                    gd.SoLuongMua = 1;
                    gd.TongTien = (double)(smv.GiaThanh * 1);

                    _context.Add(gd);
                    await _context.SaveChangesAsync();
                    ViewData["ResultGoodMessage"] = "Add to your pocket";
                    return RedirectToAction("Shopping", new { id = (int)smv.MaKhachHang});
                }
            }
            ViewData["ResultBadMessage"] = "We out of stock";
            return RedirectToAction("Shopping", "Xes", new { id = (int)smv.MaXe });
        }

        // GET: GiaoDiches
        public async Task<IActionResult> Index()
        {
            var cTQMDbContext = _context.Giaodichs.Include(g => g.KhachHang).Include(g => g.Xe);
            return View(await cTQMDbContext.ToListAsync());
        }

        // GET: GiaoDiches/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Giaodichs == null)
            {
                return NotFound();
            }

            var giaoDich = await _context.Giaodichs
                .Include(g => g.KhachHang)
                .Include(g => g.Xe)
                .FirstOrDefaultAsync(m => m.MaGiaoDich == id);
            if (giaoDich == null)
            {
                return NotFound();
            }

            return View(giaoDich);
        }

        // GET: GiaoDiches/Create
        public IActionResult Create()
        {
            ViewData["MaKhachHang"] = new SelectList(_context.KhachHangs, "MaKhachHang", "GiayPhepLaiXe");
            ViewData["MaXe"] = new SelectList(_context.Xe, "MaXe", "HangXe");
            return View();
        }

        // POST: GiaoDiches/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaGiaoDich,MaKhachHang,MaXe,SoLuongMua,TongTien")] GiaoDich giaoDich)
        {
            if (ModelState.IsValid)
            {
                _context.Add(giaoDich);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaKhachHang"] = new SelectList(_context.KhachHangs, "MaKhachHang", "GiayPhepLaiXe", giaoDich.MaKhachHang);
            ViewData["MaXe"] = new SelectList(_context.Xe, "MaXe", "HangXe", giaoDich.MaXe);
            return View(giaoDich);
        }

        // GET: GiaoDiches/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Giaodichs == null)
            {
                return NotFound();
            }

            var giaoDich = await _context.Giaodichs.FindAsync(id);
            if (giaoDich == null)
            {
                return NotFound();
            }
            ViewData["MaKhachHang"] = new SelectList(_context.KhachHangs, "MaKhachHang", "GiayPhepLaiXe", giaoDich.MaKhachHang);
            ViewData["MaXe"] = new SelectList(_context.Xe, "MaXe", "HangXe", giaoDich.MaXe);
            return View(giaoDich);
        }

        // POST: GiaoDiches/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaGiaoDich,MaKhachHang,MaXe,SoLuongMua,TongTien")] GiaoDich giaoDich)
        {
            if (id != giaoDich.MaGiaoDich)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(giaoDich);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GiaoDichExists(giaoDich.MaGiaoDich))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaKhachHang"] = new SelectList(_context.KhachHangs, "MaKhachHang", "GiayPhepLaiXe", giaoDich.MaKhachHang);
            ViewData["MaXe"] = new SelectList(_context.Xe, "MaXe", "HangXe", giaoDich.MaXe);
            return View(giaoDich);
        }

        // GET: GiaoDiches/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Giaodichs == null)
            {
                return NotFound();
            }

            var giaoDich = await _context.Giaodichs
                .Include(g => g.KhachHang)
                .Include(g => g.Xe)
                .FirstOrDefaultAsync(m => m.MaGiaoDich == id);
            if (giaoDich == null)
            {
                return NotFound();
            }

            return View(giaoDich);
        }

        // POST: GiaoDiches/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, CartModelView cmv)
        {
            if (_context.Giaodichs == null)
            {
                return Problem("Entity set 'CTQMDbContext.Giaodichs'  is null.");
            }
            var giaoDich = await _context.Giaodichs
               .FirstOrDefaultAsync(m => m.MaXe == id && m.MaKhachHang == cmv.MaKhachHang);
            if (giaoDich != null)
            {
                _context.Giaodichs.Remove((GiaoDich)giaoDich);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction("Shopping", new { id = (int)cmv.MaKhachHang });
        }

        private bool GiaoDichExists(int id)
        {
          return _context.Giaodichs.Any(e => e.MaGiaoDich == id);
        }
    }
}

CTQM_MEC/Controllers/KhachHangsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CTQM_MEC.Data;
using CTQM_Car.Data;
using CTQM_MEC.Models;
using Microsoft.AspNetCore.Authorization;

namespace CTQM_MEC.Controllers
{
    public class KhachHangsController : Controller
    {
        private readonly CTQMDbContext _context;

        public KhachHangsController(CTQMDbContext context)
        {
            _context = context;
        }

        [Authorize]
        public async Task<IActionResult> Profile(int? id)
        {
            ProfileModelView pmv = new ProfileModelView();
            if (id != null)
            {
                pmv.MaKhachHang = id;
                var khachHang = await _context.KhachHangs.FindAsync(id);
                pmv.TenKhachHang = khachHang.TenKhachHang;
                var HD = from x in _context.HoaDons
                         where x.MaKhachHang == id
                         select x;
                List<HoaDon> HDList = HD.ToList();
                List<Xe> XeList = new List<Xe>();
                for (int i = 0; i < HDList.Count; i++)
                {
                    var Car = await _context.Xe.FindAsync(HDList[i].MaXe);
                    XeList.Add(Car);
                }
                pmv.ListXe = XeList;
                return View("Cart", pmv);
            }
            return RedirectToAction("Index", "Home");
        }

        // GET: KhachHangs
        public async Task<IActionResult> Index()
        {
              return View(await _context.KhachHangs.ToListAsync());
        }

        // GET: KhachHangs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.KhachHangs == null)
            {
                return NotFound();
            }

            var khachHang = await _context.KhachHangs
                .FirstOrDefaultAsync(m => m.MaKhachHang == id);
            if (khachHang == null)
            {
                return NotFound();
            }

            return View(khachHang);
        }

        // GET: KhachHangs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: KhachHangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaKhachHang,TenKhachHang,SDT,DiaChi,NgaySinh,GiayPhepLaiXe")] KhachHang khachHang)
        {
            if (ModelState.IsValid)
            {
                _context.Add(khachHang);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(khachHang);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SignUp(VMLogin newKH)
        {
            if (ModelState.IsValid)
            {
                KhachHang kh = new KhachHang();
                kh.TenKhachHang = newKH.NewName;
                kh.SDT = newKH.NewPhone;
                kh.DiaChi = "";
                kh.NgaySinh = DateTime.Today;
                kh.GiayPhepLaiXe = "";
                kh.Email = newKH.NewEmail;
                kh.Password = newKH.Password;
                _context.Add(kh);
                await _context.SaveChangesAsync();
                return View("Access", "Login");
            }
            return View("Access", "Register");
        }

        // GET: KhachHangs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.KhachHangs == null)
            {
                return NotFound();
            }

            var khachHang = await _context.KhachHangs.FindAsync(id);
            if (khachHang == null)
            {
                return NotFound();
            }
            return View(khachHang);
        }

        // POST: KhachHangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaKhachHang,TenKhachHang,SDT,DiaChi,NgaySinh,GiayPhepLaiXe")] KhachHang khachHang)
        {
            if (id != khachHang.MaKhachHang)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(khachHang);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KhachHangExists(khachHang.MaKhachHang))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(khachHang);
        }

        // GET: KhachHangs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.KhachHangs == null)
            {
                return NotFound();
            }

            var khachHang = await _context.KhachHangs
                .FirstOrDefaultAsync(m => m.MaKhachHang == id);
            if (khachHang == null)
            {
                return NotFound();
            }

            return View(khachHang);
        }

        // POST: KhachHangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.KhachHangs == null)
            {
                return Problem("Entity set 'CTQMDbContext.KhachHangs'  is null.");
            }
            var khachHang = await _context.KhachHangs.FindAsync(id);
            if (khachHang != null)
            {
                _context.KhachHangs.Remove(khachHang);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KhachHangExists(int id)
        {
          return _context.KhachHangs.Any(e => e.MaKhachHang == id);
        }
    }
}

CTQM_MEC/Views/Shared/_CTQMLayout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width" />
	<title>CTQM Car</title>
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Lato:wght@700&family=Mohave:wght@700&family=Montserrat:wght@100;200;300;400;500;600;700&family=Nothing+You+Could+Do&display=swap" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/3.1.2/fullpage.min.css" integrity="sha512-4rPgyv5iG0PZw8E+oRdfN/Gq+yilzt9rQ8Yci2jJ15rAyBmF0HBE4wFjBkoB72cxBeg63uobaj1UcNt/scV93w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="~/css/NavFooter.css" rel="stylesheet" />
</head>

<body>
	<div class="blur__overlay"></div>

	<header class="header">
		<a class="header__left" href="/home">
			<img class="header__logo" src="~/images/CTQM_logo.png" alt="" />
		</a>

		<ul class="header__right">
			<li>
				<div class="search-container">
					<form asp-controller="xes" asp-action="search" method="get">
						<input class="search expandright" id="searchright" type="text" name="searching" placeholder="Search">
						<label class="header__nav__btn search_btn" for="searchright" type="submit" value="searching"><span class="mglass">&#9906;</span></label>
					</form>
				</div>
			</li>
			@if (Context.User.Identity.IsAuthenticated) 
			{
				<li><a class="header__nav__btn" asp-controller="GiaoDiches" asp-action="Shopping" asp-route-id=@Context.User.FindFirst(ClaimTypes.SerialNumber).Value >shop</a></li>
				<li><a class="header__nav__btn" asp-controller="KhachHangs" asp-action="Profile" asp-route-id=@Context.User.FindFirst(ClaimTypes.SerialNumber).Value >@Context.User.FindFirst(ClaimTypes.NameIdentifier).Value</a></li>
			}
			else 
			{
				<li><a class="header__nav__btn" asp-controller="GiaoDiches" asp-action="Shopping">shop</a></li>
				<li><a class="header__nav__btn" asp-controller="access" asp-action="Login">account</a></li>
			}
			<li><a class="menu__btn header__nav__btn">menu</a></li>
		</ul>
	</header>

	<nav class="navigation">
		<div class="close__btn__container">
			<img class="navigation__close__btn" src="https://thatanjan.github.io/tesla-clone-yt/media/close_icon.svg" alt="" />
		</div>
		<ul>
			<li><a class="header__nav__btn" asp-controller="xes" asp-action="Product" >New Arrival</a></li>
			<li><a class="header__nav__btn" asp-controller="xes" asp-action="Product" asp-route-type="Mercedes-EQ" >Mercedes-EQ</a></li>
			<li><a class="header__nav__btn" asp-controller="xes" asp-action="Product" asp-route-type="Mercedes-AMG" >Mercedes-AMG</a></li>
			<li><a class="header__nav__btn" asp-controller="xes" asp-action="Product" asp-route-type="Coupé" >Coupé</a></li>
			<li><a class="header__nav__btn" asp-controller="xes" asp-action="Product" asp-route-type="Mercedes-Maybach" >Mercedes-Maybach</a></li>
			@if (Context.User.Identity.IsAuthenticated) {
				<li><a class="header__nav__btn" asp-area="" asp-controller="Home" asp-action="LogOut">Logout</a></li>
			}
		</ul>
	</nav>

	<section id="fullpage">
		<section class="section number">
			<div class="section__content">
				<main role="main" class="pb-3">
					@RenderBody()
				</main>
			</div>
		</section>
	</section>
	<footer class="footer">
		<ul>
			<li><a href="">CTQM © 2022</a></li>
			<li><a href="">Privacy &amp; Legal</a></li>
			<li><a href="">2211COMP106401</a></li>
			<li><a href="">Mr.HIENLTH</a></li>
		</ul>
	</footer>
	<script src="~/js/NavFooter.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/3.1.2/fullpage.min.js" integrity="sha512-gSf3NCgs6wWEdztl1e6vUqtRP884ONnCNzCpomdoQ0xXsk06lrxJsR7jX5yM/qAGkPGsps+4bLV5IEjhOZX+gg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</body>
</html>

CTQM_MEC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CTQM_MEC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CTQM_MEC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/GioHang.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CTQM_MEC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="LogOut">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CTQM_MEC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>